CREATE DATABASE "hello_world_db"
    WITH OWNER "root"
    ENCODING 'UTF8'
    LC_COLLATE = 'en_US.UTF-8'
    LC_CTYPE = 'en_US.UTF-8'
    TEMPLATE template0;

\connect hello_world_db;

CREATE TABLE hello_world (
     id     NOT NULL generated by default as identity,
     text   VARCHAR(50) NOT NULL,
     PRIMARY KEY (id)
);