// Code generated by protoc-gen-twirp v8.1.0, DO NOT EDIT.
// source: services/todo_service.proto

package services

import context "context"
import fmt "fmt"
import http "net/http"
import ioutil "io/ioutil"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

import google_protobuf1 "google.golang.org/protobuf/types/known/emptypb"
import pepeunlimited_twirpkit_resources2 "github.com/pepeunlimited/go-twirp-starter-kit/pkg/api/v1/resources"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// =====================
// TodoService Interface
// =====================

type TodoService interface {
	CreateTodo(context.Context, *CreateTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error)

	GetTodo(context.Context, *GetTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error)

	ListTodo(context.Context, *ListTodoRequest) (*ListTodoResponse, error)

	UpdateTodo(context.Context, *UpdateTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error)

	DeleteTodo(context.Context, *DeleteTodoRequest) (*google_protobuf1.Empty, error)
}

// ===========================
// TodoService Protobuf Client
// ===========================

type todoServiceProtobufClient struct {
	client      HTTPClient
	urls        [5]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewTodoServiceProtobufClient creates a Protobuf client that implements the TodoService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewTodoServiceProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) TodoService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "pepeunlimited.twirpkit.services", "TodoService")
	urls := [5]string{
		serviceURL + "CreateTodo",
		serviceURL + "GetTodo",
		serviceURL + "ListTodo",
		serviceURL + "UpdateTodo",
		serviceURL + "DeleteTodo",
	}

	return &todoServiceProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *todoServiceProtobufClient) CreateTodo(ctx context.Context, in *CreateTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pepeunlimited.twirpkit.services")
	ctx = ctxsetters.WithServiceName(ctx, "TodoService")
	ctx = ctxsetters.WithMethodName(ctx, "CreateTodo")
	caller := c.callCreateTodo
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *CreateTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateTodoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateTodoRequest) when calling interceptor")
					}
					return c.callCreateTodo(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*pepeunlimited_twirpkit_resources2.Todo)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*pepeunlimited_twirpkit_resources2.Todo) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *todoServiceProtobufClient) callCreateTodo(ctx context.Context, in *CreateTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error) {
	out := new(pepeunlimited_twirpkit_resources2.Todo)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *todoServiceProtobufClient) GetTodo(ctx context.Context, in *GetTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pepeunlimited.twirpkit.services")
	ctx = ctxsetters.WithServiceName(ctx, "TodoService")
	ctx = ctxsetters.WithMethodName(ctx, "GetTodo")
	caller := c.callGetTodo
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetTodoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetTodoRequest) when calling interceptor")
					}
					return c.callGetTodo(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*pepeunlimited_twirpkit_resources2.Todo)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*pepeunlimited_twirpkit_resources2.Todo) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *todoServiceProtobufClient) callGetTodo(ctx context.Context, in *GetTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error) {
	out := new(pepeunlimited_twirpkit_resources2.Todo)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *todoServiceProtobufClient) ListTodo(ctx context.Context, in *ListTodoRequest) (*ListTodoResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pepeunlimited.twirpkit.services")
	ctx = ctxsetters.WithServiceName(ctx, "TodoService")
	ctx = ctxsetters.WithMethodName(ctx, "ListTodo")
	caller := c.callListTodo
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ListTodoRequest) (*ListTodoResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListTodoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListTodoRequest) when calling interceptor")
					}
					return c.callListTodo(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListTodoResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListTodoResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *todoServiceProtobufClient) callListTodo(ctx context.Context, in *ListTodoRequest) (*ListTodoResponse, error) {
	out := new(ListTodoResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *todoServiceProtobufClient) UpdateTodo(ctx context.Context, in *UpdateTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pepeunlimited.twirpkit.services")
	ctx = ctxsetters.WithServiceName(ctx, "TodoService")
	ctx = ctxsetters.WithMethodName(ctx, "UpdateTodo")
	caller := c.callUpdateTodo
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *UpdateTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdateTodoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdateTodoRequest) when calling interceptor")
					}
					return c.callUpdateTodo(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*pepeunlimited_twirpkit_resources2.Todo)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*pepeunlimited_twirpkit_resources2.Todo) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *todoServiceProtobufClient) callUpdateTodo(ctx context.Context, in *UpdateTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error) {
	out := new(pepeunlimited_twirpkit_resources2.Todo)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *todoServiceProtobufClient) DeleteTodo(ctx context.Context, in *DeleteTodoRequest) (*google_protobuf1.Empty, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pepeunlimited.twirpkit.services")
	ctx = ctxsetters.WithServiceName(ctx, "TodoService")
	ctx = ctxsetters.WithMethodName(ctx, "DeleteTodo")
	caller := c.callDeleteTodo
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *DeleteTodoRequest) (*google_protobuf1.Empty, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteTodoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteTodoRequest) when calling interceptor")
					}
					return c.callDeleteTodo(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf1.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf1.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *todoServiceProtobufClient) callDeleteTodo(ctx context.Context, in *DeleteTodoRequest) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[4], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// =======================
// TodoService JSON Client
// =======================

type todoServiceJSONClient struct {
	client      HTTPClient
	urls        [5]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewTodoServiceJSONClient creates a JSON client that implements the TodoService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewTodoServiceJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) TodoService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "pepeunlimited.twirpkit.services", "TodoService")
	urls := [5]string{
		serviceURL + "CreateTodo",
		serviceURL + "GetTodo",
		serviceURL + "ListTodo",
		serviceURL + "UpdateTodo",
		serviceURL + "DeleteTodo",
	}

	return &todoServiceJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *todoServiceJSONClient) CreateTodo(ctx context.Context, in *CreateTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pepeunlimited.twirpkit.services")
	ctx = ctxsetters.WithServiceName(ctx, "TodoService")
	ctx = ctxsetters.WithMethodName(ctx, "CreateTodo")
	caller := c.callCreateTodo
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *CreateTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateTodoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateTodoRequest) when calling interceptor")
					}
					return c.callCreateTodo(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*pepeunlimited_twirpkit_resources2.Todo)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*pepeunlimited_twirpkit_resources2.Todo) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *todoServiceJSONClient) callCreateTodo(ctx context.Context, in *CreateTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error) {
	out := new(pepeunlimited_twirpkit_resources2.Todo)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *todoServiceJSONClient) GetTodo(ctx context.Context, in *GetTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pepeunlimited.twirpkit.services")
	ctx = ctxsetters.WithServiceName(ctx, "TodoService")
	ctx = ctxsetters.WithMethodName(ctx, "GetTodo")
	caller := c.callGetTodo
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetTodoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetTodoRequest) when calling interceptor")
					}
					return c.callGetTodo(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*pepeunlimited_twirpkit_resources2.Todo)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*pepeunlimited_twirpkit_resources2.Todo) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *todoServiceJSONClient) callGetTodo(ctx context.Context, in *GetTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error) {
	out := new(pepeunlimited_twirpkit_resources2.Todo)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *todoServiceJSONClient) ListTodo(ctx context.Context, in *ListTodoRequest) (*ListTodoResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pepeunlimited.twirpkit.services")
	ctx = ctxsetters.WithServiceName(ctx, "TodoService")
	ctx = ctxsetters.WithMethodName(ctx, "ListTodo")
	caller := c.callListTodo
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ListTodoRequest) (*ListTodoResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListTodoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListTodoRequest) when calling interceptor")
					}
					return c.callListTodo(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListTodoResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListTodoResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *todoServiceJSONClient) callListTodo(ctx context.Context, in *ListTodoRequest) (*ListTodoResponse, error) {
	out := new(ListTodoResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *todoServiceJSONClient) UpdateTodo(ctx context.Context, in *UpdateTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pepeunlimited.twirpkit.services")
	ctx = ctxsetters.WithServiceName(ctx, "TodoService")
	ctx = ctxsetters.WithMethodName(ctx, "UpdateTodo")
	caller := c.callUpdateTodo
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *UpdateTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdateTodoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdateTodoRequest) when calling interceptor")
					}
					return c.callUpdateTodo(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*pepeunlimited_twirpkit_resources2.Todo)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*pepeunlimited_twirpkit_resources2.Todo) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *todoServiceJSONClient) callUpdateTodo(ctx context.Context, in *UpdateTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error) {
	out := new(pepeunlimited_twirpkit_resources2.Todo)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *todoServiceJSONClient) DeleteTodo(ctx context.Context, in *DeleteTodoRequest) (*google_protobuf1.Empty, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pepeunlimited.twirpkit.services")
	ctx = ctxsetters.WithServiceName(ctx, "TodoService")
	ctx = ctxsetters.WithMethodName(ctx, "DeleteTodo")
	caller := c.callDeleteTodo
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *DeleteTodoRequest) (*google_protobuf1.Empty, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteTodoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteTodoRequest) when calling interceptor")
					}
					return c.callDeleteTodo(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf1.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf1.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *todoServiceJSONClient) callDeleteTodo(ctx context.Context, in *DeleteTodoRequest) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[4], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ==========================
// TodoService Server Handler
// ==========================

type todoServiceServer struct {
	TodoService
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewTodoServiceServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewTodoServiceServer(svc TodoService, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &todoServiceServer{
		TodoService:      svc,
		hooks:            serverOpts.Hooks,
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:       pathPrefix,
		jsonSkipDefaults: jsonSkipDefaults,
		jsonCamelCase:    jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *todoServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *todoServiceServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// TodoServicePathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const TodoServicePathPrefix = "/twirp/pepeunlimited.twirpkit.services.TodoService/"

func (s *todoServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "pepeunlimited.twirpkit.services")
	ctx = ctxsetters.WithServiceName(ctx, "TodoService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "pepeunlimited.twirpkit.services.TodoService" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "CreateTodo":
		s.serveCreateTodo(ctx, resp, req)
		return
	case "GetTodo":
		s.serveGetTodo(ctx, resp, req)
		return
	case "ListTodo":
		s.serveListTodo(ctx, resp, req)
		return
	case "UpdateTodo":
		s.serveUpdateTodo(ctx, resp, req)
		return
	case "DeleteTodo":
		s.serveDeleteTodo(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *todoServiceServer) serveCreateTodo(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveCreateTodoJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveCreateTodoProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *todoServiceServer) serveCreateTodoJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CreateTodo")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(CreateTodoRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.TodoService.CreateTodo
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *CreateTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateTodoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateTodoRequest) when calling interceptor")
					}
					return s.TodoService.CreateTodo(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*pepeunlimited_twirpkit_resources2.Todo)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*pepeunlimited_twirpkit_resources2.Todo) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *pepeunlimited_twirpkit_resources2.Todo
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *pepeunlimited_twirpkit_resources2.Todo and nil error while calling CreateTodo. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *todoServiceServer) serveCreateTodoProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CreateTodo")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(CreateTodoRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.TodoService.CreateTodo
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *CreateTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateTodoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateTodoRequest) when calling interceptor")
					}
					return s.TodoService.CreateTodo(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*pepeunlimited_twirpkit_resources2.Todo)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*pepeunlimited_twirpkit_resources2.Todo) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *pepeunlimited_twirpkit_resources2.Todo
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *pepeunlimited_twirpkit_resources2.Todo and nil error while calling CreateTodo. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *todoServiceServer) serveGetTodo(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetTodoJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetTodoProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *todoServiceServer) serveGetTodoJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetTodo")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(GetTodoRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.TodoService.GetTodo
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetTodoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetTodoRequest) when calling interceptor")
					}
					return s.TodoService.GetTodo(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*pepeunlimited_twirpkit_resources2.Todo)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*pepeunlimited_twirpkit_resources2.Todo) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *pepeunlimited_twirpkit_resources2.Todo
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *pepeunlimited_twirpkit_resources2.Todo and nil error while calling GetTodo. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *todoServiceServer) serveGetTodoProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetTodo")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(GetTodoRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.TodoService.GetTodo
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetTodoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetTodoRequest) when calling interceptor")
					}
					return s.TodoService.GetTodo(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*pepeunlimited_twirpkit_resources2.Todo)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*pepeunlimited_twirpkit_resources2.Todo) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *pepeunlimited_twirpkit_resources2.Todo
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *pepeunlimited_twirpkit_resources2.Todo and nil error while calling GetTodo. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *todoServiceServer) serveListTodo(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveListTodoJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveListTodoProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *todoServiceServer) serveListTodoJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListTodo")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(ListTodoRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.TodoService.ListTodo
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ListTodoRequest) (*ListTodoResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListTodoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListTodoRequest) when calling interceptor")
					}
					return s.TodoService.ListTodo(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListTodoResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListTodoResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ListTodoResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListTodoResponse and nil error while calling ListTodo. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *todoServiceServer) serveListTodoProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListTodo")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(ListTodoRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.TodoService.ListTodo
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ListTodoRequest) (*ListTodoResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListTodoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListTodoRequest) when calling interceptor")
					}
					return s.TodoService.ListTodo(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListTodoResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListTodoResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ListTodoResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListTodoResponse and nil error while calling ListTodo. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *todoServiceServer) serveUpdateTodo(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveUpdateTodoJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveUpdateTodoProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *todoServiceServer) serveUpdateTodoJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "UpdateTodo")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(UpdateTodoRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.TodoService.UpdateTodo
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *UpdateTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdateTodoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdateTodoRequest) when calling interceptor")
					}
					return s.TodoService.UpdateTodo(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*pepeunlimited_twirpkit_resources2.Todo)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*pepeunlimited_twirpkit_resources2.Todo) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *pepeunlimited_twirpkit_resources2.Todo
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *pepeunlimited_twirpkit_resources2.Todo and nil error while calling UpdateTodo. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *todoServiceServer) serveUpdateTodoProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "UpdateTodo")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(UpdateTodoRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.TodoService.UpdateTodo
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *UpdateTodoRequest) (*pepeunlimited_twirpkit_resources2.Todo, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdateTodoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdateTodoRequest) when calling interceptor")
					}
					return s.TodoService.UpdateTodo(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*pepeunlimited_twirpkit_resources2.Todo)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*pepeunlimited_twirpkit_resources2.Todo) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *pepeunlimited_twirpkit_resources2.Todo
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *pepeunlimited_twirpkit_resources2.Todo and nil error while calling UpdateTodo. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *todoServiceServer) serveDeleteTodo(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveDeleteTodoJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveDeleteTodoProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *todoServiceServer) serveDeleteTodoJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeleteTodo")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(DeleteTodoRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.TodoService.DeleteTodo
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *DeleteTodoRequest) (*google_protobuf1.Empty, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteTodoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteTodoRequest) when calling interceptor")
					}
					return s.TodoService.DeleteTodo(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf1.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf1.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *google_protobuf1.Empty
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *google_protobuf1.Empty and nil error while calling DeleteTodo. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *todoServiceServer) serveDeleteTodoProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeleteTodo")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(DeleteTodoRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.TodoService.DeleteTodo
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *DeleteTodoRequest) (*google_protobuf1.Empty, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteTodoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteTodoRequest) when calling interceptor")
					}
					return s.TodoService.DeleteTodo(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf1.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf1.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *google_protobuf1.Empty
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *google_protobuf1.Empty and nil error while calling DeleteTodo. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *todoServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor1, 0
}

func (s *todoServiceServer) ProtocGenTwirpVersion() string {
	return "v8.1.0"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *todoServiceServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "pepeunlimited.twirpkit.services", "TodoService")
}

var twirpFileDescriptor1 = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0xc7, 0x95, 0x96, 0x6e, 0xeb, 0x55, 0x6c, 0xd4, 0x9a, 0xa0, 0x4a, 0x85, 0xa8, 0xfa, 0x30,
	0x15, 0x89, 0xda, 0xac, 0x3c, 0x21, 0xf1, 0x02, 0x1b, 0x20, 0x24, 0x90, 0x50, 0x36, 0x24, 0x04,
	0x0f, 0x55, 0xba, 0x5c, 0x53, 0x2b, 0x69, 0x6c, 0x6c, 0x67, 0x8c, 0x7d, 0x02, 0x1e, 0x79, 0xe0,
	0x03, 0xa3, 0x38, 0xcd, 0x42, 0x1b, 0xa1, 0x66, 0xe2, 0x2d, 0x3e, 0xdf, 0xdd, 0xff, 0xef, 0xbb,
	0x9f, 0x02, 0x7d, 0x8d, 0xea, 0x92, 0x5f, 0xa0, 0x66, 0x46, 0x04, 0x62, 0xba, 0x3a, 0x51, 0xa9,
	0x84, 0x11, 0xe4, 0x91, 0x44, 0x89, 0x69, 0x12, 0xf3, 0x25, 0x37, 0x18, 0x50, 0xf3, 0x9d, 0x2b,
	0x19, 0x71, 0x43, 0x8b, 0x1a, 0xb7, 0x1f, 0x0a, 0x11, 0xc6, 0xc8, 0x6c, 0xfa, 0x2c, 0x9d, 0x33,
	0x5c, 0x4a, 0xf3, 0x23, 0xaf, 0x76, 0x07, 0x9b, 0x97, 0x73, 0x8e, 0x71, 0x30, 0x5d, 0xfa, 0x3a,
	0x5a, 0x65, 0x1c, 0x2a, 0xd4, 0x22, 0x55, 0x85, 0x7a, 0x1e, 0x1d, 0x3e, 0x86, 0xee, 0x89, 0x42,
	0xdf, 0xe0, 0xb9, 0x08, 0x84, 0x87, 0xdf, 0x52, 0xd4, 0x86, 0x1c, 0x42, 0xcb, 0x70, 0x13, 0x63,
	0xcf, 0x19, 0x38, 0xa3, 0xb6, 0x97, 0x1f, 0x86, 0x5f, 0x61, 0xff, 0x2d, 0x9a, 0xbf, 0xf3, 0xf6,
	0xa1, 0xc1, 0x03, 0x9b, 0xd4, 0xf4, 0x1a, 0x3c, 0x20, 0xcf, 0x01, 0x4a, 0xd9, 0x5e, 0x63, 0xe0,
	0x8c, 0x3a, 0x13, 0x97, 0xe6, 0xce, 0x68, 0xe1, 0x8c, 0xbe, 0xc9, 0x52, 0x3e, 0xf8, 0x3a, 0xf2,
	0xda, 0xf3, 0xe2, 0x73, 0xf8, 0xd3, 0x81, 0x83, 0xf7, 0x5c, 0xaf, 0xb5, 0xef, 0x43, 0x5b, 0xfa,
	0x21, 0x4e, 0x35, 0xbf, 0xce, 0xad, 0xb4, 0xbc, 0xbd, 0x2c, 0x70, 0xc6, 0xaf, 0x91, 0x3c, 0x04,
	0xb0, 0x97, 0x46, 0x44, 0x98, 0x58, 0xad, 0xa6, 0x67, 0xd3, 0xcf, 0xb3, 0xc0, 0x86, 0x95, 0xe6,
	0x6d, 0xac, 0x5c, 0xc1, 0xbd, 0xd2, 0x89, 0x96, 0x22, 0xd1, 0x48, 0x5e, 0x40, 0x2b, 0x1b, 0x9a,
	0xee, 0x39, 0x83, 0xe6, 0xa8, 0x33, 0x39, 0xa2, 0xff, 0x58, 0xd6, 0xcd, 0x8c, 0xa9, 0x2d, 0xcf,
	0x8b, 0xc8, 0x11, 0x1c, 0x24, 0x78, 0x65, 0xa6, 0x15, 0xc3, 0x77, 0xb3, 0xf0, 0xc7, 0xc2, 0xf4,
	0xf0, 0xb7, 0x03, 0xdd, 0x4f, 0x32, 0xd8, 0xd8, 0xc6, 0x29, 0xb4, 0x85, 0x44, 0xe5, 0x1b, 0x2e,
	0x12, 0x3b, 0x86, 0xfa, 0xfa, 0x65, 0xe1, 0xff, 0xec, 0xe6, 0x09, 0x74, 0x4f, 0x31, 0xc6, 0x75,
	0x57, 0x0f, 0x60, 0xd7, 0x42, 0x7c, 0x03, 0xc0, 0x4e, 0x76, 0x7c, 0x17, 0x4c, 0x7e, 0xdd, 0x81,
	0x4e, 0x96, 0x78, 0x96, 0x73, 0x4b, 0x16, 0x00, 0x25, 0x61, 0x64, 0x42, 0xb7, 0x60, 0x4e, 0x2b,
	0x38, 0xba, 0x35, 0x5f, 0x4b, 0x66, 0xb0, 0xbb, 0x02, 0x94, 0xb0, 0xad, 0x32, 0xeb, 0x28, 0xd7,
	0xd6, 0x10, 0xb0, 0x57, 0xc0, 0x41, 0x9e, 0x6e, 0x15, 0xd9, 0x20, 0xda, 0x3d, 0xbe, 0x45, 0xc5,
	0x8a, 0xbc, 0x05, 0x40, 0x89, 0x44, 0x8d, 0xf1, 0x55, 0xf8, 0xa9, 0xfd, 0xb4, 0xcf, 0x00, 0xe5,
	0x9a, 0x6b, 0x28, 0x55, 0x98, 0x70, 0xef, 0x57, 0x78, 0x7a, 0x9d, 0xfd, 0xa2, 0x5e, 0x9d, 0x7c,
	0x79, 0x19, 0x72, 0xb3, 0x48, 0x67, 0xf4, 0x42, 0x2c, 0xd9, 0x5a, 0x5f, 0x16, 0x8a, 0xb1, 0x6d,
	0x3d, 0xd6, 0xc6, 0x57, 0x06, 0xd5, 0x38, 0xe2, 0x86, 0xc9, 0x28, 0x64, 0xbe, 0xe4, 0xec, 0xf2,
	0x98, 0x15, 0x72, 0xb3, 0x1d, 0xdb, 0xf4, 0xd9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x30,
	0xe9, 0xd2, 0x45, 0x05, 0x00, 0x00,
}
